### PR TITLE
fixed shapes before Ax+Bu calc

### PR DESCRIPTION
**Pull request by dgrunberg**
This is a fix for issue20 - it forces the shapes of the inputs to xdot = Ax+Bu calculation in LTI_SS to be (N,1) so that inputs such as [1.0] and [array([1.0])] both work correctly.

make test produces
 115 passed, 1 skipped, 11 warnings in 0.51s

### CODE REVIEW

**Comment by dgrunberg** [comment]
Adding an assert that the inputs are what is expected would be a way to make sure other blocks output the correct shaped signals and thus finding other problems, at the risk of causing fails for users.

**Review by petercorke — CHANGES_REQUESTED** [review]
comment implies x and u are (N,1), perhaps say convert to column vectors

u is always a list of 1D ndarrays so strictly u doesn't need to be reshaped, but doesn't hurt to be sure.

x definitely needs reshaping, thanks

**Comment by dgrunberg** [comment]
The output from STEP is a list of a float:  [1.0], while the output of INTEGRATOR is a list of 1D ndarrays:  [np.array([1.0]) ].  After np.array(), these change to shapes of (1,) and (1,1), respectively.  This is why the broadcasting happens.

I update the comment to indicate column vectors, and removed the extraneous np.array on u.

**Comment by dgrunberg** [comment]
I did a sync with your master, then pulled in all your recent changes and somehow those got committed as changes and are in this pull request.  Not sure if I should have done that, I apologize.  Let me know if I should fix that or maybe start over with a clean pull request?

**Comment by petercorke** [comment]
Dan, I think this will duplicate commits already in place.  It's a small change that I could make, but if you want to do a cleaner PR I'd be happy to accept it.  Thx

**Comment by dgrunberg** [comment]
Will do, no problem

On Jul 9, 2023, at 5:16 PM, Peter Corke ***@***.******@***.***>> wrote:



Dan, I think this will duplicate commits already in place. It's a small change that I could make, but if you want to do a cleaner PR I'd be happy to accept it. Thx

**Review by petercorke — APPROVED** [review]

**Review by petercorke — APPROVED** [review]

**Comment by petercorke** [comment]
Thanks Dan, this one closed.  Please keep providing feedback and PRs :)

**Pull request merged**
